more_words = ['trump',
              'biden',
              'maga',
              'bidenharris', 
              'kamala',
              'pence',
              'harris',
              'mike',
              'usa',
              'ivoted',
              'realdonaldtrump',
              'americans',
             ]