multi_words = [
    (r"god bless america", "god_bless_america"),
    (r"god bless", "god_bless"),
    (r"vote joe biden", "vote_joe_biden"),
    (r"trump supporter", "trump_supporter"),
    (r"biden supporter", "biden_supporter"),
    (r"student loan debt", "student_loan_debt"),
    (r"student loan", "student_loan"),
    (r"universal health care", "universal_health_care"),
    (r"universalhealthcare", "universal_health_care"),
    (r"health care", "health_care"),
    (r"healthcare", "health_care"),
    (r"supreme court", "supreme_court"),
    (r"campaign trail", "campaign_trail"),
    (r"pack the court", "pack_the_court"),
    (r"cant stop", "cant_stop"),
    (r"executive order", "executive_order"),
    (r"white supremist", "white_supremist"),
    (r"hate speech", "hate_speech"),
    (r"come together", "come_together"),
    (r"climate change", "climate_change"),
    (r"global warming", "global_warming"),
    (r"middle east", "middle_east"),
    (r"north korea", "north_korea"),
    (r"fox news", "foxnews"),
    (r"rights", "gun_rights"),
    (r"take away our guns", "take_away_our_guns"),
    (r"vote blue", "vote_blue"),
    (r"vote donald trump", "vote_donald_trump"),
    (r"vote trump", "vote_donald_trump"),
    (r"vote red", "vote_red"),
    (r"voting red", "vote_red"),
    (r"voting blue", "vote_blue"),
    (r'voter supression', 'voter_supression'),
    (r'hispanic vote', 'hispanic_vote'),
    (r'white vote', 'white_vote'),
    (r'hispanic vote', 'hispanic_vote'),
    (r'people of color', 'people_of_color'),
    (r'corrupt politician', 'corrupt_politician'),
    (r'whole world', 'whole_world'),
    (r'last election', 'last_election'),
    (r'stock market', 'stock_market'),
    (r'orange man', 'orange_man'),
    (r'violent crime', 'violent_crime'),
    (r'defund the police', 'defund_the_police'),
    (r'campaign rally', 'campaign_rally'),
    (r'violent protest', 'violent_protest'),
    (r'violent protests', 'violent_protest'),
    (r'cover up', 'cover_up'),
    (r"vice president", "vice_president"),
    (r"domestic terrorism", "domestic_terrorism"),
    (r"conspiracy theory", "conspiracy_theory"),
    (r"go vote", "go_vote"),
    (r"go away", "go_away"),
    (r"far left", "far_left"),
    (r"far right", "far_right"),
    (r"left wing", "left_wing"),
    (r"domestic terrorism", "domestic_terrorism"),
    (r"conspiracy theory", "conspiracy_theory"),
    (r"campaign stop", "campaign_stop"),
    (r"far left", "far_left"),
    (r"far right", "far_right"),
    (r"left wing", "left_wing"),
    (r"right wing", "right_wing"),
    (r"electoral college", "electoral_college"),
    (r"russian interference", "russian_inteference"),
    (r"foreign interference", "foreign_inteference"),    
    (r"social inequality", "social_inequality"),
    (r"joebiden", "joe_biden"),
    (r"hunterbiden", "hunter_biden"),
    (r"hunter biden", "hunter_biden"),
    (r"ivankatrump", "ivanka_trump"),
    (r"ivanka trump", "ivanka_trump"),
    (r"erictrump", "eric_trump"),
    (r"eric trump", "eric_trump"),
    (r"trump crime family", "trump_crime_family"),
    (r"biden crime family", "biden_crime_family"),
    (r"travel restriction", "travel_restriction"),
    (r"stay at home order", "stay_at_home_order"),
    (r"lock down", "lock_down"),
    (r"tik tok", "tiktok"),
    (r"legal vote", "legal_vote"),
    (r"law enforcement", "law_enforcement"),
    (r"kamalaharris", "kamala_harris"),
    (r"president trump", "donald_trump"),
    (r"president donald trump", "donald_trump"),
    (r"vice president mike pence", "mike_pence"),
    (r"vice president pence", "mike_pence"),
    (r"vice president kamala harris", "kamala_harris"),
    (r"vice president harris", "kamala_harris"),
    (r"vice president", "vice_president"),
    (r"voting rights", "voting_rights"),
    (r"donaldtrump", "donald_trump"),
    (r"mikepence", "mike_pence"),
    (r"joe biden", "joe_biden"),
    (r"kamala harris", "kamala_harris"),
    (r"donald trump", "donald_trump"),
    (r"mike pence", "mike_pence"),
    (r"nancy pelosi", "nancy_pelosi"),
    (r"mitch mcconnell", "mitch_mcconnell"),
    (r"\bbiden\b", "joe_biden"),
    (r"\bpence\b", "mike_pence"),
    (r"\bharris\b", "kamala_harris"),
    (r"\btrump\b", "donald_trump"),
    (r"coronavirus outbreak", "coronavirus_outbreak"),
    (r"anthonyfauci", "anthony_fauci"),
    (r"anthony fauci", "anthony_fauci"),
    (r"\bfauci\b", "anthony_fauci"),
    (r"\bjoe\b", "joe_biden"),
    (r"\bkamala\b", "kamala_harris"),
    (r"\bdonald\b", "donald_trump"),
    (r"united states of america", "usa"),
    (r"democratic presidential nominee", "democratic_presidential_nominee"),
    (r"republican presidential nominee", "republican_presidential_nominee"),
    (r"democratic party", "democratic_party"),
    (r"republican party", "republican_party"),
    (r"red state", "red_state"),
    (r"raise tax", "raise_tax"),
    (r"increase tax", "raise_tax"),
    (r"communications director", "communications_director"),
    (r"lower tax", "reduce_tax"),
    (r"lower tax", "reduce_tax"),
    (r"reduce tax", "reduce_tax"),
    (r"blue state", "blue_state"),
    (r"planned parenthood", "planned_parenthood"),
    (r"minimum wage", "minimum_wage"),
    (r"absentee ballot", "absentee_ballot"),
    (r"drain the swamp", "drain_the_swamp"),
    (r"hillary clinton", "hillary_clinton"),
    (r"\bhillary\b", "hillary_clinton"),
    (r"barack obama", "barack_obama"),
    (r"\bobama\b", "barack_obama"),
    (r"abortion rights", "abortion_rights"),
    (r"pro life", "prolife"),
    (r"pro choice", "prochoice"),
    (r"come together", "come_together"),
    (r"rise up", "rise_up"),
    (r"hate speech", "hate_speech"),
    (r"public health", "public_health"),
    (r"go home", "go_home"),
    (r"first lady", "first_lady"),
    (r"black lives matter", "black_lives_matter"),
    (r"blm", "black_lives_matter"),
    (r"blacklivesmatter", "black_lives_matter"),
    (r"all lives matter", "all_lives_matter"),
    (r"blue lives matter", "blue_lives_matter"),
    (r"mailin ballot", "mail_in_ballot"),
    (r"mailin", "mail_in_ballot"),
    (r"united states", "usa"),
    (r"attorney general", "attorney_general"),
    (r"white house", "white_house"),
    (r"unite for a better america", "unite_for_a_better_america"),
    (r"commander and chief", "commander_and_chief"),
    (r"make america great again", "maga"),
    (r"makeamericagreatagain", "maga"),
    (r"election fraud", "election_fraud"),
    (r"sleepy joe biden", "sleepy_joe"),
    (r"sleepy joe", "sleepy_joe"),
    (r"presidential election", "election"),
    (r"running mate", "running_mate"),
    (r"voting machine", "voting_machine"),
    (r"cast your ballot", "cast_your_ballot"),
    (r"foreign policy", "foreign_policy"),
    (r"election day", "election_day"),
    (r"voting booth", "voting_booth"),
    (r"radical left", "radical_left"),
    (r"free speech", "free_speech"),
    (r"first amendment", "first_amendment"),
    (r"racial injustice", "racial_injustice"),
    (r"go time", "go_time")
]
