multi_words = [
    (r'voter supression', 'voter_supression'),
    (r'hispanic vote', 'hispanic_vote'),
    (r'white vote', 'white_vote'),
    (r'hispanic vote', 'hispanic_vote'),
    (r'black women', 'black_women'),
    (r'white women', 'white_women'),
    (r'white men', 'white_men'),
    (r'black men', 'black_men'),
    (r'black voters', 'black_voters'),
    (r'white voters', 'white_voters'),
    (r'people of color', 'people_of_color'),
    (r'whole world', 'whole_world'),
    (r'stock market', 'stock_market'),
    (r'orange man', 'orange_man'),
    (r'campaign rally', 'campaign_rally'),
    (r'violent protest', 'violent_protest'),
    (r'violent protests', 'violent_protest'),
    (r'cover up', 'cover_up'),
    (r"vice president", "vice_president"),
    (r"domestic terrorism", "domestic_terrorism"),
    (r"conspiracy theory", "conspiracy_theory"),
    (r"far left", "far_left"),
    (r"far right", "far_right"),
    (r"left wing", "left_wing")
]
