multi_words = [
    (r"god bless america", "godblessamerica"),
    (r"god bless", "godbless"),
    (r"fake news media", "fakenewsmedia"),
    (r"fake news", "fakenews"),
    (r"vote joe biden", "votejoebiden"),
    (r"trump supporter", "trumpsupporter"),
    (r"biden supporter", "bidensupporter"),
    (r"student loan debt", "studentloandebt"),
    (r"student loan", "studentloan"),
    (r"universal health care", "universalhealthcare"),
    (r"universal healthcare", "universalhealthcare"),
    (r"health care", "healthcare"),
    (r"supreme court", "supremecourt"),
    (r"campaign trail", "campaigntrail"),
    (r"pack the court", "packthecourt"),
    (r"cant stop", "cantstop"),
    (r"executive order", "executiveorder"),
    (r"white supremacy", "whitesupremacy"),
    (r"white supremacist", "whitesupremacist"),
    (r"hate speech", "hatespeech"),
    (r"come together", "cometogether"),
    (r"climate change", "climatechange"),
    (r"global warming", "globalwarming"),
    (r"middle east", "middleeast"),
    (r"north korea", "northkorea"),
    (r"fox news", "foxnews"),
    (r"rights", "gunrights"),
    (r"take away our guns", "takeawayourguns"),
    (r"vote blue", "voteblue"),
    (r"vote donald trump", "votedonaldtrump"),
    (r"vote trump", "votedonaldtrump"),
    (r"vote red", "votered"),
    (r"voting red", "votered"),
    (r"voting blue", "voteblue"),
    (r'voter supression', 'votersupression'),
    (r'hispanic vote', 'hispanicvote'),
    (r'white vote', 'whitevote'),
    (r'hispanic vote', 'hispanicvote'),
    (r'people of color', 'peopleofcolor'),
    (r'corrupt politician', 'corruptpolitician'),
    (r'whole world', 'wholeworld'),
    (r'last election', 'lastelection'),
    (r'stock market', 'stockmarket'),
    (r'orange man', 'orangeman'),
    (r'violent crime', 'violentcrime'),
    (r'defund the police', 'defundthepolice'),
    (r'campaign rally', 'campaignrally'),
    (r'violent protest', 'violentprotest'),
    (r'violent protests', 'violentprotest'),
    (r'cover up', 'coverup'),
    (r"vice president", "vicepresident"),
    (r"domestic terrorism", "domesticterrorism"),
    (r"conspiracy theory", "conspiracytheory"),
    (r"go vote", "govote"),
    (r"go away", "goaway"),
    (r"far left", "farleft"),
    (r"far right", "farright"),
    (r"left wing", "leftwing"),
    (r"domestic terrorism", "domesticterrorism"),
    (r"conspiracy theory", "conspiracytheory"),
    (r"campaign stop", "campaignstop"),
    (r"far left", "farleft"),
    (r"far right", "farright"),
    (r"left wing", "leftwing"),
    (r"right wing", "rightwing"),
    (r"electoral college", "electoralcollege"),
    (r"russian interference", "russianinteference"),
    (r"foreign interference", "foreigninteference"),    
    (r"social inequality", "socialinequality"),
    (r"hunter biden", "hunterbiden"),
    (r"ivanka trump", "ivankatrump"),
    (r"eric trump", "erictrump"),
    (r"trump crime family", "trumpcrimefamily"),
    (r"biden crime family", "bidencrimefamily"),
    (r"travel restriction", "travelrestriction"),
    (r"stay at home order", "stayathomeorder"),
    (r"lock down", "lockdown"),
    (r"tik tok", "tiktok"),
    (r"legal vote", "legalvote"),
    (r"law enforcement", "lawenforcement"),
    (r"president trump", "donaldtrump"),
    (r"president donald trump", "donaldtrump"),
    (r"vice president mike pence", "mikepence"),
    (r"vice president pence", "mikepence"),
    (r"vice president kamala harris", "kamalaharris"),
    (r"vice president harris", "kamalaharris"),
    (r"vice president", "vicepresident"),
    (r"voting rights", "votingrights"),
    (r"joe biden", "joebiden"),
    (r"kamala harris", "kamalaharris"),
    (r"donald trump", "donaldtrump"),
    (r"mike pence", "mikepence"),
    (r"nancy pelosi", "nancypelosi"),
    (r"mitch mcconnell", "mitchmcconnell"),
    (r"\bbiden\b", "joebiden"),
    (r"\bpence\b", "mikepence"),
    (r"\bharris\b", "kamalaharris"),
    (r"\btrump\b", "donaldtrump"),
    (r"coronavirus outbreak", "coronavirusoutbreak"),
    (r"anthony fauci", "anthonyfauci"),
    (r"\bfauci\b", "anthonyfauci"),
    (r"\bjoe\b", "joebiden"),
    (r"\bkamala\b", "kamalaharris"),
    (r"\bdonald\b", "donaldtrump"),
    (r"united states of america", "usa"),
    (r"democratic presidential nominee", "democraticpresidentialnominee"),
    (r"republican presidential nominee", "republicanpresidentialnominee"),
    (r"democratic party", "democraticparty"),
    (r"republican party", "republicanparty"),
    (r"red state", "redstate"),
    (r"raise tax", "raisetax"),
    (r"increase tax", "raisetax"),
    (r"communications director", "communicationsdirector"),
    (r"lower tax", "reducetax"),
    (r"lower tax", "reducetax"),
    (r"reduce tax", "reducetax"),
    (r"blue state", "bluestate"),
    (r"planned parenthood", "plannedparenthood"),
    (r"minimum wage", "minimumwage"),
    (r"absentee ballot", "absenteeballot"),
    (r"drain the swamp", "draintheswamp"),
    (r"hillary clinton", "hillaryclinton"),
    (r"\bhillary\b", "hillaryclinton"),
    (r"barack obama", "barackobama"),
    (r"\bobama\b", "barackobama"),
    (r"abortion rights", "abortionrights"),
    (r"pro life", "prolife"),
    (r"pro choice", "prochoice"),
    (r"come together", "cometogether"),
    (r"rise up", "riseup"),
    (r"hate speech", "hatespeech"),
    (r"public health", "publichealth"),
    (r"go home", "gohome"),
    (r"first lady", "firstlady"),
    (r"black lives matter", "blacklivesmatter"),
    (r"blm", "blacklivesmatter"),
    (r"all lives matter", "alllivesmatter"),
    (r"blue lives matter", "bluelivesmatter"),
    (r"mailin ballot", "mailinballot"),
    (r"mailin", "mailinballot"),
    (r"united states", "usa"),
    (r"attorney general", "attorneygeneral"),
    (r"white house", "whitehouse"),
    (r"unite for a better america", "uniteforabetteramerica"),
    (r"commander and chief", "commanderandchief"),
    (r"make america great again", "maga"),
    (r"election fraud", "electionfraud"),
    (r"sleepy joe biden", "sleepyjoe"),
    (r"sleepy joe", "sleepyjoe"),
    (r"presidential election", "election"),
    (r"running mate", "runningmate"),
    (r"voting machine", "votingmachine"),
    (r"cast your ballot", "castyourballot"),
    (r"foreign policy", "foreignpolicy"),
    (r"election day", "electionday"),
    (r"voting booth", "votingbooth"),
    (r"radical left", "radicalleft"),
    (r"free speech", "freespeech"),
    (r"first amendment", "firstamendment"),
    (r"racial injustice", "racialinjustice"),
    (r"go time", "gotime")
]
